name: Sync fork with upstream
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - uses: thiagokokada/merge-upstream@v1.0.2
        with:
          branch: master
          token: ${{ secrets.WORKFLOW_PAT }}
